name: Monthly Report

on:
  push:
    branches-ignore:
      - master
  schedule:
    # 08:00 AM Eastern year round
    - cron: "0 13 1 * *"
  workflow_dispatch:
    inputs:
      skip_fetch:
        description: "skip fetching GitHub data"
        type: boolean
        default: false

jobs:
  run-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Download issue/PR data and run analysis scripts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_FETCH: ${{ contains(github.event.head_commit.message,
            '[skip fetch]') || github.event.inputs.skip_fetch == 'true' }}
        run: |
          python -m issues_metrics.run_reports

      - name: Commit updated data
        run: |
          MONTH_YEAR=$(date +"%B %Y")
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add issues_metrics/*.pkl
          git add issues_metrics/report_data/*.pkl

          if [ "${{ github.event_name }}" == "schedule" ]; then
            COMMIT_MESSAGE="Monthly issue/PR data upload for $MONTH_YEAR"
          else
            COMMIT_MESSAGE="Manual issue/PR run"
          fi

          git commit -m "$COMMIT_MESSAGE" \
            || echo "No changes to commit"
          git push
